# fly.toml app configuration file generated for funcalv4 on 2026-02-07T23:48:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'funcalv4'
primary_region = 'sjc'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = 'bin/rails db:migrate'

[processes]
  web = 'bundle exec puma -C config/puma.rb'
  worker = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  processes = ['web']
  size = 'shared-cpu-1x'
  memory = '512mb'

[[vm]]
  processes = ['worker']
  size = 'shared-cpu-1x'
  memory = '512mb'
